image:
  repository: k8s-debug-agent
  tag: latest
  pullPolicy: IfNotPresent

ai:
  # provider: openai | gemini
  provider: openai
  # model name hints for your app (not enforced by chart)
  model: "gpt-4o"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true

env:
  # One of these must be set, depending on provider
  OPENAI_API_KEY: ""
  GOOGLE_API_KEY: ""

secret:
  create: true
  name: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

podAnnotations: {}

podSecurityContext: {}

securityContext:
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

extraArgs: []

extraEnv: []