{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "k8s-debug-agent.fullname" .) .Values.secret.name }}
type: Opaque
stringData:
  {{- if .Values.env.OPENAI_API_KEY }}
  OPENAI_API_KEY: "{{ .Values.env.OPENAI_API_KEY }}"
  {{- end }}
  {{- if .Values.env.GOOGLE_API_KEY }}
  GOOGLE_API_KEY: "{{ .Values.env.GOOGLE_API_KEY }}"
  {{- end }}
{{- end }}