{{- if and .Values.secret.create (or .Values.env.OPENAI_API_KEY (hasKey .Values.env "OPENAI_API_KEY")) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "k8s-debug-agent.fullname" .) .Values.secret.name }}
type: Opaque
stringData:
  OPENAI_API_KEY: "{{ .Values.env.OPENAI_API_KEY }}"
{{- end }}